### ISSUE TITLE
Tune up final token offering list.

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#105]
Review /website/src/data/TokenList.json vs. Joey's latest list, deleting low-liquidity coins and so-on.  Finalize for beta.  We're a few weeks short in the production file vs. Joey's latest list.  Square it up.

**Comment by ctrl030** [comment]
updated TokenList and created PR for newest version 👍

**Comment by orbitmechanic** [comment]
Just a touch of copy/paste "stickiness" between 1Inch and Mana's image...
![Screen Shot 2021-11-04 at 5 45 43 PM](https://user-images.githubusercontent.com/56613757/140424718-c3795e3a-34ed-4329-b306-b7868ac1517f.png)

**Comment by ctrl030** [comment]
fixed and updated and created PR,  "smart contracts 127" is the newest version

**Comment by orbitmechanic** [comment]
Looks good!
