### ISSUE TITLE
Auto-add tokens we're swapping into into MetaMask list (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#115]
Enough said?

**Comment by git-tn** [comment]
@orbitmechanic , I've reviewed the swap and Metamask list and it seems there's little delay on auto-add, if it's causing problem, we may use [`@metamask/detect-provider`](https://docs.metamask.io/guide/ethereum-provider.html#methods) to force Metamask sync list.

**Comment by orbitmechanic** [comment]
<img width="812" alt="Screen Shot 2021-11-30 at 4 19 21 PM" src="https://user-images.githubusercontent.com/56613757/144130317-44fe653b-5b33-4d74-a98f-15c7f44507ba.png">
<img width="631" alt="Screen Shot 2021-11-30 at 4 19 39 PM" src="https://user-images.githubusercontent.com/56613757/144130349-00072d1b-2e78-4bf1-ba6b-9632f1e9181d.png">
Brilliant!  Works great.
Well...actually it's not entirely automated.  The end user still has to approve.  But I think that's the best MetaMask will allow...for now....
