### ISSUE TITLE
Audit Moralis API vs. Moralis security (6 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#117]
Tune it up vs. https://docs.moralis.io/moralis-server/database/security#parse-security-summary

**Comment by orbitmechanic** [comment]
Critical bugs inspected.  They turned out to be code used for dev and testing, nothing that deploys.

**Comment by nyousaf47** [comment]
I reviewed and listen their videos, Read their docs about Securities. 
I have seen all tables in our DB and then have to discuss with you guys , what should be public/private/protected.

**Comment by orbitmechanic** [comment]
3 levels of protection are available:
-Whole table: allow only user sessions to modify user records.
-Object level: allow users to only see their records.
-Field level: password fields can be protected.

**Comment by orbitmechanic** [comment]
<img width="535" alt="Screen Shot 2021-12-10 at 7 09 54 AM" src="https://user-images.githubusercontent.com/56613757/145572120-737f090f-9cbf-4100-a2bf-6ce01fb9c2ba.png">
Production settings.  Class level permissions.
When a new request comes all public can read, only authenticated can write a record, and nobody can add a field.

**Comment by orbitmechanic** [comment]
Meanwhile on transactions: script can add records, but public readable only:
<img width="532" alt="Screen Shot 2021-12-10 at 7 14 30 AM" src="https://user-images.githubusercontent.com/56613757/145572618-8eaddd23-e0ef-466f-81b0-88928319afaf.png">

**Comment by orbitmechanic** [comment]
Video resources from Moralis: 
https://docs.moralis.io/moralis-server/database/security

**Comment by orbitmechanic** [comment]
Server fields locked
![Screen Shot 2021-12-29 at 9 06 29 AM](https://user-images.githubusercontent.com/56613757/147670612-47e0634a-79d4-4c64-ac8a-e0f66e62f58e.png)
.

**Comment by orbitmechanic** [comment]
File uploads disabled in cloud functions.
![Screen Shot 2021-12-29 at 9 08 48 AM](https://user-images.githubusercontent.com/56613757/147670682-5f95f79d-41f9-4dab-9776-8bc2ad9bda4a.png)
