### ISSUE TITLE
Fix the login button (expand and stupify)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#123]
The login button needs to be huge.
Make it look like a web3 app.

**Comment by nyousaf47** [comment]
<img width="434" alt="Screenshot 2021-11-09 at 12 14 57 PM" src="https://user-images.githubusercontent.com/31923141/140960220-ac1d31cd-a1a9-40eb-b74b-cfce78270328.png">
<img width="335" alt="Screenshot 2021-11-09 at 12 15 09 PM" src="https://user-images.githubusercontent.com/31923141/140960233-aa8458b9-9cbd-486e-82ed-9283b63775ea.png">

**Comment by orbitmechanic** [comment]
Looks great on my machine too:
<img width="603" alt="Screen Shot 2021-11-09 at 4 48 44 PM" src="https://user-images.githubusercontent.com/56613757/141010438-a6dace70-1f13-4947-908d-e0d8e3b4912e.png">
.
