### ISSUE TITLE
Deal with users tabbing out of website mid-swap post authorization. (10 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#145]
Consider posting a broswer-wide alert for when users need to approve Tx after they've approved the ...uh..."approval" Tx.

Also: can we force focus to return to the MetaMask extension pop-up when we need it to.

Also consider locking focus to the MetaMask until we release it (after Tx is resolved).

Reconsider forcing MetaMask into an iFrame on our page.

**Comment by rumi-art** [comment]
Hi @orbitmechanic, Should show alert before this action?
![image](https://user-images.githubusercontent.com/76024390/143396946-0e019e8a-0815-4a16-b4ec-46910d0a28a3.png)

**Comment by rumi-art** [comment]
And i think we can't control focus until Tx is resolved.

**Comment by orbitmechanic** [comment]
O.B.E.
