### ISSUE TITLE
Check Moralis synch with Metamask network on startup (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#154]
<img width="747" alt="Screen Shot 2021-11-17 at 10 17 45 AM" src="https://user-images.githubusercontent.com/56613757/142229569-7eab7c8b-8585-4234-a8b2-b0b219860796.png">
I received this portfolio display of my Ethereum address upon logging in when my MetaMask was clearly displaying my Polygon balance...?

**Comment by orbitmechanic** [comment]
The portfolio swaps are now instant with respect to MetaMask network changes.  Well done!

**Comment by orbitmechanic** [comment]
Not tracking yet.  This happened to me today: Ethereum portfolio while MetaMask is displaying Polygon.  MetaMask claims Polygon is connected.
<img width="836" alt="Screen Shot 2021-11-19 at 1 55 27 PM" src="https://user-images.githubusercontent.com/56613757/142676536-d0e982df-3a4c-44c5-9204-de0bfdb4c220.png">

**Comment by rumi-art** [comment]
It doesn't happen for me.

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-22 at 8 49 15 PM](https://user-images.githubusercontent.com/56613757/142960571-93ee611e-86dd-4374-ac1a-9519b4be5134.png)
Ok, so last time I logged in with Polygon in my MetaMask it went straight there.  But there's this weird MetaMask "Connect" button, when it's clearly connected.  If I press the "Connect"  button it disappears.  Not sure if this is the same issue anymore.
