### ISSUE TITLE
Handle failed tokenBalance request.

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#155]
I've been getting this result lately: portfolio balance with no portfolio.  Console log has failed query, code 400's.  We should handle those and re-issue the requests.
<img width="1291" alt="Screen Shot 2021-11-17 at 10 25 56 AM" src="https://user-images.githubusercontent.com/56613757/142230208-1b16b602-1dd3-4036-93c0-7e5add52b059.png">

**Comment by orbitmechanic** [comment]
This issue miraculously resolved itself.  Was it a Moralis server maintenance event?  Is there a ping we can do to show the server status?

**Comment by git-tn** [comment]
I think so. It seems a Moralis server problem.

**Comment by rumi-art** [comment]
error: "required param address not provided" I am getting this error yet.
I think api is called before login first. I will check it again.

**Comment by orbitmechanic** [comment]
I see the code to fix this.  However the Moralis network is up and running so I can't test it under real conditions.  We shall see, if Moralis goes down again (Incidentally they blamed Uniswap or somesuch on their forum).

**Comment by orbitmechanic** [comment]
This just happened to me.  Got weird.  Failed getNativeBalance() call.  Aborted the portfolio display, left it with some incorrect balance (due to the oops between META and Matic in the getTokenBallance()
<img width="1146" alt="Screen Shot 2021-11-19 at 1 42 54 PM" src="https://user-images.githubusercontent.com/56613757/142675413-6fdddd87-5a62-4f3c-ae15-cd26c2e7c63a.png">

**Comment by rumi-art** [comment]
I will check and fix.

**Comment by rumi-art** [comment]
Seems it looks different with my side. Which branch are you using?
![image_2021_11_19T19_34_23_607Z](https://user-images.githubusercontent.com/76024390/142681553-7aaf1a2b-c443-46be-aa1e-3c0bbdeee4dd.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-22 at 10 11 58 AM](https://user-images.githubusercontent.com/56613757/142885952-7f6dde15-c8fe-4dea-afb5-f897c521faf9.png)
Looks great! Thank you!
