### ISSUE TITLE
Clear Moralis session automagically when logging out. (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#162]
Ok for starters when I log in with my MetaMask on Polygon I get this weird state: Moralis is still logged in from my last session, that should be cleared, and Moralis thinks my MetaMask is on Ethereum.  I think this would clear up if closing the website automagically logs the user out of their Moralis session.  My hypothesis is that the Moralis session from the previous web session is holding on to the stale MetaMask network state. To test this: rig the whole site so that it fires a Moralis logout automatically upon closing.  Probably much safer that way anyway.

![Screen Shot 2021-11-22 at 9 42 33 AM](https://user-images.githubusercontent.com/56613757/142881472-0de99fae-a9f7-4f72-a9c3-5c1f82ad66fe.png)

**Comment by orbitmechanic** [comment]
Logging Moralis in does not resolve the mainnet vs. Polygon issue:
![Screen Shot 2021-11-22 at 9 47 03 AM](https://user-images.githubusercontent.com/56613757/142881832-6e5afbff-98bf-44f7-81a0-00b0d29abb73.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-22 at 9 01 40 PM](https://user-images.githubusercontent.com/56613757/142961059-7f05cc09-694f-4d0a-99f7-c543f9f4759d.png)
This is the state I now get when I:

1. Start localhost and the web page.
2. Authenticate with MetaMask (on Polygon).
3. Close the webpage/browser tab.
4. Reopen a new browser tab.
5. Log into localhost:3000 again.

It's got a weird MetaMask "Connect" button in the header (#165), and it's retained the Moralis session from the previous browser tab.  It should reset to the blank log-in screen with no connections.

**Comment by rumi-art** [comment]
@orbitmechanic I followed your words here on my side but couldn't regenerate those bugs... so weird.

**Comment by orbitmechanic** [comment]
Works fine now!  Good job!
![Screen Shot 2021-11-23 at 11 58 32 AM](https://user-images.githubusercontent.com/56613757/143075857-0bdef1a6-9840-410b-b65a-c7245d9a4d37.png)
