### ISSUE TITLE
Create expert stage for mobile (8 hours) 

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#176]
Create an expert stage to display:
-configurable dialog with a setDialog function
-"Expert" icon art avatar
-Milestone component (development pending)
-Additional image or video component (optional)

**Comment by nyousaf47** [comment]
@rumi-art  before to start work on this let me know first. 
I have started this and worked on it, it was related to my ticket.

**Comment by orbitmechanic** [comment]
O.B.E.
