### ISSUE TITLE
Retune Transak widget in buy/sell (12 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#194]
<img width="1190" alt="Screen Shot 2021-11-30 at 5 22 02 PM" src="https://user-images.githubusercontent.com/56613757/144137875-ea9add53-38a9-45df-ba8f-7a831e6f2b53.png">
Something's gone wrong with our Transak widget.  Not sure if its on our end or theirs anymore.  Have a look.  They say we're approved on their end.  But testing...doesn't seem to make it that far.

**Comment by git-tn** [comment]
Hey @orbitmechanic , were you able to make netlify deployment? if you were able to, please update the env var `REACT_APP_TRANSAK_API_KEY` to production Key. then it should work fine. if you are still experiencing same issue with production key, then let's sync again.

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-12-02 at 8 17 54 PM](https://user-images.githubusercontent.com/56613757/144528374-fe9e06f0-8a63-464b-b8d5-db9ded88a4de.png)
Getting veeeery close.  This one bounced off my bank.  That's an internal fiat problem.  I think we're done with this one.  It's working as well as we can make it work.
