### ISSUE TITLE
Evaluate underscore dependency (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#215]
Evaluate if this code is deployed to the user.  If so update as needed.
<img width="874" alt="Screen Shot 2021-12-06 at 1 19 11 PM" src="https://user-images.githubusercontent.com/56613757/144900396-1e06e420-1fb1-49d9-93df-e47db96fbd89.png">

**Comment by nyousaf47** [comment]
this is duplicate

**Comment by orbitmechanic** [comment]
Closed to PR
