### ISSUE TITLE
Break login screen out as its own route (8 hours) 

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#243]
The login screen needs to be its own route suitable for including in an iFrame on the marketing website.

**Comment by orbitmechanic** [comment]
Layout as per design team specs for our login or sign-up page.  
Note: in the design doc both light and dark modes have dark mode backgrounds/color scheme.
<img width="655" alt="Screen Shot 2021-12-09 at 9 50 10 AM" src="https://user-images.githubusercontent.com/56613757/145418651-0d3ed6fa-1b69-48cc-ab49-133b13ccd869.png">

**Comment by orbitmechanic** [comment]
Note: omit fingerprint support in the mobile ap for now.  Let's not require system components just yet until we have to.

**Comment by orbitmechanic** [comment]
Awaiting fix of linter issue before I can merge the PR.

**Comment by nyousaf47** [comment]
done

**Comment by orbitmechanic** [comment]
<img width="305" alt="Screen Shot 2021-12-15 at 6 16 22 PM" src="https://user-images.githubusercontent.com/56613757/146279701-8f876cce-d59a-4dc4-b07a-a5637cc6e588.png">
Beautiful!  And it works too!
