### ISSUE TITLE
Expert dismiss panel button no longer works ( 1 hour )

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#265]
![image](https://user-images.githubusercontent.com/56613757/146035754-aedfce8b-5dcd-4250-9fd4-1c52b51decc2.png)

**Comment by nyousaf47** [comment]
@orbitmechanic  please mention browser, on which you are facing. 
Its working on chrome.

**Comment by orbitmechanic** [comment]
Works now!
