### ISSUE TITLE
Fix the Decentraland Icon ( 1 hr )

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#268]
It's hash.

**Comment by nyousaf47** [comment]
can you put screen shot here? i mixed this ticket i think @orbitmechanic?

**Comment by orbitmechanic** [comment]
![image](https://user-images.githubusercontent.com/56613757/146611697-8e058a5e-8d26-4422-85b1-918afe161852.png)
Looks good!  Thank you!
