### ISSUE TITLE
Tune up Trading view sources (6 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#297]
1.) Set default time scale to 1 day (currently 1 hour)
2.) Force as many pairs to source from CoinBase as are available.

**Comment by orbitmechanic** [comment]
Coinbase preferred followed by Binance.us, then Kracken...then uniswap, then whatever.

**Comment by orbitmechanic** [comment]
Check TradingView widget API to see if it allows us to specify an exchange to source the data from.

**Comment by git-tn** [comment]
TradingView does not support filtering sources, I went through their API detail docs and they don't support it. It's all or only one.

**Comment by orbitmechanic** [comment]
TradingView widget API does not support sources.  Confirmed.
