### ISSUE TITLE
Fix the update password button on the log-in screen (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#304]
The update password button is locked inactive.

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-12-22 at 11 09 45 AM](https://user-images.githubusercontent.com/56613757/147121871-65421bde-3cda-4433-8b9c-cd7d0d76a91f.png)

**Comment by rumi-art** [comment]
@orbitmechanic We need to setup server to send email for resetPassword.
Can you make sure this (setting up server for sending email). https://docs.moralis.io/moralis-server/tools/sending-email
I added code into front-end.

**Comment by orbitmechanic** [comment]
Very good. I will set that up soon.

**Comment by orbitmechanic** [comment]
Ok, I've set that up USAWallet's SendGrid account, and the Verification and Password Reset template.  I'll post the API key to Discord.  I've added REACT_APP_SENDGRID_API_KEY to Netlify as well.  Give it a try. 
<img width="745" alt="Screen Shot 2021-12-27 at 10 49 17 AM" src="https://user-images.githubusercontent.com/56613757/147487300-41397017-0ce2-4287-8478-77ae4388e860.png">
<img width="680" alt="Screen Shot 2021-12-27 at 10 49 46 AM" src="https://user-images.githubusercontent.com/56613757/147487344-1203b8a2-0f76-4bd6-a02b-53aedf763cf9.png">

**Comment by orbitmechanic** [comment]
<img width="823" alt="Screen Shot 2021-12-27 at 12 33 16 PM" src="https://user-images.githubusercontent.com/56613757/147494622-414fd439-c807-4d1a-9948-fd904f571a50.png">
Works
<img width="609" alt="Screen Shot 2021-12-27 at 12 34 24 PM" src="https://user-images.githubusercontent.com/56613757/147494702-1ff01ffc-9847-4e93-8e57-4d55de5b9959.png">
Still some work to do on SendGrid, but it's mostly working.  I'll put that up as another issue.
