### ISSUE TITLE
Add the "Details" field to the token data card (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#309]
Add a "Details:" heading below the Trading View widget on the data card.
Add a ".details" field to TokenData.json and source it from the [USAWallet token data repository.](https://docs.google.com/document/d/1T0DIkantdvaSKlWr1dRJAAEtccClXFjBmc071DyCr_A/edit?usp=sharing).  Display it below the new "Details" heading on the token data card.

**Comment by nyousaf47** [comment]
@orbitmechanic can you tell me what details i have to copy from google?
<img width="742" alt="Screenshot 2021-12-24 at 9 06 14 AM" src="https://user-images.githubusercontent.com/31923141/147314971-506cdb19-014a-488f-a846-19a772a86fbe.png">

**Comment by orbitmechanic** [comment]
Looks great!
![Screen Shot 2021-12-29 at 8 38 52 AM](https://user-images.githubusercontent.com/56613757/147668084-10be5b91-4251-4cfe-92cb-7c41e59c2c55.png)
