### ISSUE TITLE
Lock Transak to ONLY USDC/Polygon.  Ditch DAI etc. (1 hour)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#323]
![image](https://user-images.githubusercontent.com/56613757/147769874-5d634ec3-36ca-4170-a6f5-628186d531d9.png)
Get rid of any option but USD to USDC on Polygon.
Set to ONLY in our parameters.

**Comment by rumi-art** [comment]
@orbitmechanic I tested transak with changing query params but it is not showing as you want.

**Comment by rumi-art** [comment]
@orbitmechanic  I hope you can check this issue again. I don't think we can make it to show only USDC based on Transak

**Comment by orbitmechanic** [comment]
Transak parameters do not allow us to lock users out of the network selection dialog box.  Consider masking it off with iFrame mask functions.
