### ISSUE TITLE
Move MetaMask connection to Trade page (6 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#330]
- In order to simplify USA Wallet for the "old money" generation we will no longer offer "Use MetaMask" at the beginning of the session.  This just confused users in the beta test.
- Users will only be authenticated via user name and password.
- Move MetaMask connection request/demand to inside the Trade screen's "do it" button.  This is the only place where we actually need MetaMask.

**Comment by rumi-art** [comment]
Hi @orbitmechanic Porfolio & Send pages needs to login with metamask too because those are using positions.

**Comment by orbitmechanic** [comment]
OBE #330
