### ISSUE TITLE
Change the home page token to a horizontal carolsel of cards (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#345]
Per the status meeting conversation.  

Otherwise, free reign on design creativity.

**Comment by orbitmechanic** [comment]
![image](https://user-images.githubusercontent.com/56613757/148797915-f2c8efcc-be43-4431-aa2e-63a66062da8e.png)
So two things:
The list should loop.  There should be no end in either direction.
Can we get arrows on either side to indicate continuation?
Thanks!

**Comment by orbitmechanic** [comment]
<img width="613" alt="Screen Shot 2022-01-11 at 9 00 45 AM" src="https://user-images.githubusercontent.com/56613757/148956614-02f075ca-7021-4acd-b2fe-ba2be6a78f80.png">
<img width="659" alt="Screen Shot 2022-01-11 at 9 01 25 AM" src="https://user-images.githubusercontent.com/56613757/148956689-b3bb9380-766c-4a0b-ac85-4a1f2f0e7ece.png">
Well ok...
Arrows: check.
The last card is the first in a loop: check.
But...
The arrows are practically invisible in light mode.  They need to be HUGE because ...'MERICA!
Um....there seems to be only 3 cards now.

**Comment by git-tn** [comment]
Fixed arrow issue (color). 

> there seems to be only 3 cards now

Please refresh

**Comment by orbitmechanic** [comment]
Note everything works great if you're signed in with MetaMask.
Want it to run w/o MetaMask.

**Comment by orbitmechanic** [comment]
Works great w/o Metamask now.
Except...some of the cards are in a weird skeleton.
![image](https://user-images.githubusercontent.com/56613757/149804002-60ca4adb-37ac-4b2a-89f5-8d6898aa1801.png)

**Comment by orbitmechanic** [comment]
Works brilliantly now!  Great job!
