### ISSUE TITLE
Clean up reaction to disconnecting MetaMask (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#346]
Enable smooth transition for disconnecting MetaMask during a Moralis session.

**Comment by nyousaf47** [comment]
@orbitmechanic, I am not getting , what is the issue and i have to do with that?
Can you help me in this?

**Comment by orbitmechanic** [comment]
![image](https://user-images.githubusercontent.com/56613757/148799869-227ecf5f-d389-4e79-9c07-91be15281ece.png)
Our new operating model is disconnected from MetaMask Except for the trading Do it! button.
All other screens need to operate w/o metamask connection by sourcing address data from Moralis.io records.
Remove the auto-reconnect to MetaMask message as well...unless we're executing a trade.

**Comment by orbitmechanic** [comment]
Should be resolved elsewhere when updating our network context checks.
