### ISSUE TITLE
Create a page with nothing but a "log into MetaMask" button showing. (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#347]
Create a page with nothing but the "Add MetaMask to your browser" button.
Create a page with nothing but the "Add Polygon to MetaMask" button.

**Comment by nyousaf47** [comment]
https://usawallet.app/crypto-login
<img width="795" alt="Screenshot 2022-01-07 at 10 21 05 PM" src="https://user-images.githubusercontent.com/31923141/148582037-0f6d1c89-23a4-43df-99f8-93b2c367a2b5.png">

**Comment by orbitmechanic** [comment]
Very nice!
