### ISSUE TITLE
Fix ToSelect issue (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#348]
This is likely related to not signing into MetaMask.  But this was working this morning and now it's not.
![image](https://user-images.githubusercontent.com/56613757/148423952-28428811-54aa-43c6-ba19-63923c70f8c9.png)

**Comment by nyousaf47** [comment]
@orbitmechanic  can you mention steps to reproduce?

**Comment by nyousaf47** [comment]
I fixed, it looks like issue was due to Empty Value, Because, we are integrating Metamask on Trade/Portfolio now.

**Comment by orbitmechanic** [comment]
Likely in our Portfolio context in trying to source address from MetaMask.
