### ISSUE TITLE
Connect the "Reset password button" to the Moralis function from the drawer version (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#372]
![image](https://user-images.githubusercontent.com/56613757/149805074-e450637f-76ba-4e35-bef8-fa4df70839d2.png)
Connect the "Reset password" button to the function from the old drawer version.
Test w/ your account make sure it sends you something.

**Comment by nyousaf47** [comment]
It is working now and sending link in email to reset password. All configuration done.

<img width="1111" alt="Screenshot 2022-01-19 at 5 18 46 PM" src="https://user-images.githubusercontent.com/31923141/150128862-c0f795d5-b85d-4cfb-ae77-4048b9642bd3.png">

**Comment by orbitmechanic** [comment]
![image](https://user-images.githubusercontent.com/56613757/150162985-4abf173b-0bd0-42d4-bf1e-d096f00a3452.png)
![image](https://user-images.githubusercontent.com/56613757/150163371-15d1ed36-0454-4686-a14b-69022b41a8ae.png)
Confirmed!  Well done!
