### ISSUE TITLE
Fix the e-mail verification path (4 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#376]
Make sure the e-mail verification path works from a new e-mail, receive, verify, and record in the server records.

**Comment by nyousaf47** [comment]
It is also working, if you signup with an email/password, it is sending a welcome email and mentioning that to verify email in that. Verify button is also working. 
<img width="1110" alt="Screenshot 2022-01-19 at 5 18 59 PM" src="https://user-images.githubusercontent.com/31923141/150129059-12ca290a-59d6-4288-895a-88835bb892eb.png">
<img width="1117" alt="Screenshot 2022-01-19 at 5 18 23 PM" src="https://user-images.githubusercontent.com/31923141/150129073-a1366330-1ad1-4989-a90f-2d636c83511d.png">

**Comment by orbitmechanic** [comment]
Confirmed!  Well done.
![image](https://user-images.githubusercontent.com/56613757/150162662-e8f93473-00db-4fa2-845b-3d084281a5d1.png)
![image](https://user-images.githubusercontent.com/56613757/150162734-3d156a6e-d173-4ef2-92c5-b57bc30af7df.png)
