### ISSUE TITLE
Redirect all missing MetaMask and/or Polygon network issues to Marketing onboarding page (1 hour)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#385]

**Comment by orbitmechanic** [comment]
Check on log-in for the conditions below and redirect to mid-stage page.

In all three cases they should see the on-boarding page (ala recycled Nadeem's page)
-Add Expert Stage
-Character is Uncle Sam

This should happen upon:
-New user log-in before home page (Moralis has no user address)
    Dialog is ("Let's equip you to explore the cryptocurrency universe.  Press below for instructions"
-Old user switching browsers (Moralis HAS a user address, but web3 won't connect to MetaMask)
    Dialog is ("We've not equipped this browser to explore the cryptocurrency universe.  Press below for instructions"
-Or old user not completing Polygon add (Moralis has user address, web3 connects, but no polygon).
    Dialog is ("Let's complete your equipment for exploring the cryptocurrency universe")

-  Button below is "Press here to continue"

URL to redirect in all cases: https://www.usawallet.org/USA-Wallet-Onboarding

**Comment by nyousaf47** [comment]
@orbitmechanic
1. if a new user signup and he don't have address/ metamask then user need to move to mid-stage page and then redirect to above url?
2. When we are redirecting, we are logging out the current user?

**Comment by orbitmechanic** [comment]
1.) Yes on all counts.  That's this case:
-New user log-in before home page (Moralis has no user address)
Dialog is ("Let's equip you to explore the cryptocurrency universe. Press below for instructions"
2.) Yes.  Any and all exits from usawallet.app end the Moralis session and require re-log in for security reasons.
   -Please add a "(You will be required to re-log into USA Wallet for security reasons.)" under the "Press here to continue" button.

**Comment by orbitmechanic** [comment]
Define "New user" as Moralis does not have a wallet address for them.  -> redirect on startup to Marketing onboarding.
Define "mobile user" as Moralis DOES have a wallet address, so defer MetaMask check until trade DO IT button.
