### ISSUE TITLE
Comment out the email verification push (1 hour)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#386]
The "landing" website built in duda and its SEO/marketing services will exclusively handle e-mail verification (and tracking).  To avoid sending the user 2 "please verify your email"...emails: comment out but do not delete this function from usawallet.app code.

**Comment by nyousaf47** [comment]
@orbitmechanic If we will remove template id here , it will auto stop sending emails.

<img width="782" alt="Screenshot 2022-01-20 at 9 48 42 PM" src="https://user-images.githubusercontent.com/31923141/150384011-c1b2e70f-d133-4474-9bd4-9f4215c0c5aa.png">

**Comment by orbitmechanic** [comment]
Concur.
