### ISSUE TITLE
Install a "Add Polygon to MetaMask" button somewhere.

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#72]
Detect the current [chainId from Moralis](https://docs.moralis.io/moralis-server/web3/web3#getchainid).
Use the [Moralis function](https://docs.moralis.io/moralis-server/web3/web3#addnetwork) to add polygon and then [switch Moralis to Polkgon](https://docs.moralis.io/moralis-server/web3/web3#switchnetwork) if we're not already pointing to it.  
Consider my [version 1 button](https://github.com/orbitmechanic/USAMobile/blob/master/website/src/components/Scrapbox/AddNetworkButton.jsx) that I had working earlier.

Ideally this should all happen automagically upon logging in.  Otherwise drop a button to do it all onto the portfolio page.

**Comment by nyousaf47** [comment]
I tried to add Polygon Network from this Website's Button. 
It is also adding in same way and showing **?** mark on network. 

<img width="1435" alt="Screenshot 2021-11-02 at 9 40 22 PM" src="https://user-images.githubusercontent.com/31923141/139908007-d8c262be-8a5f-4e4c-85cc-618ca4db6ba6.png">
<img width="357" alt="Screenshot 2021-11-02 at 9 42 08 PM" src="https://user-images.githubusercontent.com/31923141/139908467-c5229e01-92f8-439c-8564-927b50a867a2.png">

**Comment by orbitmechanic** [comment]
Resolving/continuing as Issue #94
