### ISSUE TITLE
Swap and Send need to check that MetaMask is connected to Polygon not ETH main network.

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#79]
![Screen Shot 2021-10-31 at 9 44 14 PM](https://user-images.githubusercontent.com/56613757/139666505-2b3969c5-b1b0-4d80-a66a-fe7be26b082b.png)
Also looks like we forgot to remove the token's decimals from the amount.

**Comment by orbitmechanic** [comment]
Contingent on #90

**Comment by nyousaf47** [comment]
I already added checks , if user is on these pages, should be polygon selected @rumi-art  you can just review once again and check if need to fix any things. 
Otherwise it should work.

**Comment by rumi-art** [comment]
There are some issues in Send/Receive part. if user rejects from Metamask, button loading doesn't stop. I will check & fix, other things too.

**Comment by orbitmechanic** [comment]
I've confirmed that the new Moralis version of Send auto-reloads ETH if the user switches networks in MetaMask.  Moralis will not allow Tx's to be sent across networkId's.   That's sufficient for send....need to check Swap.
![Screen Shot 2021-11-04 at 1 16 17 PM](https://user-images.githubusercontent.com/56613757/140388673-0f62babd-ae7a-4212-962a-779e5bf22fcf.png)

**Comment by orbitmechanic** [comment]
Testing confirms this auto-requests MetaMask network change instantly if network isn't right.
