### ISSUE TITLE
Fix Transak or switch back to Moralis-> onRamper -> Moonpay (6 hours, once Transak moves)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#82]
Transak is seeing it's API, but is failing with the following:
![Screen Shot 2021-11-01 at 8 13 05 AM](https://user-images.githubusercontent.com/56613757/139669950-c68d8eaf-8bca-4353-a9fe-23983a013f1c.png)
![Screen Shot 2021-11-01 at 8 07 34 AM](https://user-images.githubusercontent.com/56613757/139669954-90d6060c-ad58-4ac1-8048-f4455161ee1e.png)
![Screen Shot 2021-11-01 at 8 08 21 AM](https://user-images.githubusercontent.com/56613757/139669958-9ef642d0-51b0-45cb-b377-1d33703ccb8b.png)
![Screen Shot 2021-11-01 at 8 09 08 AM](https://user-images.githubusercontent.com/56613757/139669962-55f83f54-36e3-4469-ad65-7d2e52bbc482.png)
![Screen Shot 2021-11-01 at 8 09 20 AM](https://user-images.githubusercontent.com/56613757/139669965-ecf9ec79-e453-4394-ab9b-b611aaa62a15.png)
![Screen Shot 2021-11-01 at 8 09 58 AM](https://user-images.githubusercontent.com/56613757/139669969-00fd6ef7-5826-4b33-a1d8-38dddae522a3.png)
![Screen Shot 2021-11-01 at 8 10 43 AM](https://user-images.githubusercontent.com/56613757/139669973-7b36215f-3a44-4347-864d-dd83fb700db0.png)
![Screen Shot 2021-11-01 at 8 12 31 AM](https://user-images.githubusercontent.com/56613757/139669975-bf99c913-f464-45d3-804e-8359d080b8f7.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-01 at 9 17 16 AM](https://user-images.githubusercontent.com/56613757/139677728-b13cefc5-a6b6-4ca0-b831-26469444a52f.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-01 at 9 58 39 AM](https://user-images.githubusercontent.com/56613757/139683492-eb7dd4b9-9121-4ada-be15-e00bc2bfda2c.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-05 at 8 28 24 AM](https://user-images.githubusercontent.com/56613757/140510311-c382463a-16dd-4479-8c73-d1bf8c707e96.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-15 at 6 21 38 PM](https://user-images.githubusercontent.com/56613757/141868195-04f90bc0-9fca-4386-acc8-04ac44c5a796.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-11-15 at 6 21 51 PM](https://user-images.githubusercontent.com/56613757/141868216-803672dc-f000-4c19-bf9e-80047bbca6b5.png)

**Comment by orbitmechanic** [comment]
![Screen Shot 2021-12-02 at 8 17 54 PM](https://user-images.githubusercontent.com/56613757/144529434-6b5c3646-a908-4511-bac9-3fad50ad5b35.png)
Currently crashing in fiat against my bank.  I think we've gone about as far as we can.  Service request to Transak now.

**Comment by kumar-transak** [comment]
are your issues fixed wrt to Integration and order processing or still open. Please let me know, I can initiate some efforts here.
