### ISSUE TITLE
Send "ToAddress" component never unlocks.

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#90]
Um...we can't test out of several other issues because this is blocking.
![Screen Shot 2021-11-02 at 11 49 27 AM](https://user-images.githubusercontent.com/56613757/139884175-082159e7-1776-4f10-acb9-59bd7ee0a0c9.png)

**Comment by nyousaf47** [comment]
@orbitmechanic  I need console message of this. 
i don't think we should face this issue after my changes. 
Because we are changing/Switching Network to Polygon and hiding/Disabling ENS.
Console message can help me to find the issue.

**Comment by rumi-art** [comment]
![image](https://user-images.githubusercontent.com/76024390/139909551-687ad757-9671-4ede-ba1e-3ff16edde7db.png)

**Comment by orbitmechanic** [comment]
Yes, I get this exact same ENS error in my console.log

**Comment by orbitmechanic** [comment]
Seems to be fixed for now.
![Screen Shot 2021-11-03 at 11 26 17 AM](https://user-images.githubusercontent.com/56613757/140093456-5c9993da-f5c7-4ec7-995f-d976e4902d91.png)
